TX_DB_PATH = "./db/tx"
TX_TEST_DB_PATH = "./db/tx_test"
ROOT_DB_PATH = "./db/root"
CRON_DB_PATH = "./db/cron"
TX_RECEIPT_DB_PATH = "./db/receipt"
METADATA_DB_PATH = "./db/metadata"
METACONTRACT_DB_PATH = "./db/metacontract"
TX_KEY = "tx"
CRON_KEY = "cron"
TX_RECEIPT_KEY = "receipt"
METADATA_KEY = "metadata"
METACONTRACT_KEY = "metacontract"
# RQLITE ENDPOINTS
SQL_EXECUTE = "http://localhost:4001/db/execute"
SQL_QUERY = "http://localhost:4001/db/query?associative"